language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: limitless-everglades-24506
  api_key: ${HEROKU_API_KEY}
